from enum import StrEnum


class NodeType(StrEnum):
    EVENT = "event"
    CHARACTER = "character"
    PLANET = "planet"
    FACTION = "faction"


class RelationshipType(StrEnum):
    CAUSES = "CAUSES"
    INVOLVES = "INVOLVES"
    LOCATED_IN = "LOCATED_IN"
    MEMBER_OF = "MEMBER_OF"
    ALLIED_WITH = "ALLIED_WITH"
    ENEMY_OF = "ENEMY_OF"
    SETS_ALIVE_STATE = "SETS_ALIVE_STATE"
    SETS_CHARACTER_LOCATION = "SETS_CHARACTER_LOCATION"
    SETS_PLANET_CONTROL = "SETS_PLANET_CONTROL"
    SETS_ARTIFACT_LOCATION = "SETS_ARTIFACT_LOCATION"
